# SRM Export Targets
targets:
  - target_id: SRM-EXPORT-PDF
    format: PDF
    output_path: ../EXPORT/PDF
  - target_id: SRM-EXPORT-HTML
    format: HTML
    output_path: ../EXPORT/HTML
  - target_id: SRM-EXPORT-IETP
    format: IETP_PACKAGE
    output_path: ../EXPORT/IETP_PACKAGE
